### ISSUE TITLE
Is it possible to generate the dll files of the projects to access the functions from unity

### ISSUE THREAD

**Issue by akilaVis** [SuavePirate/Xamarin.WebRTC#1]
Hi and thank you for the code!

I want to ask you if it is possible to generate the dll files of xamarin project (android, ios, uwp) to be used in unity, I mean build the projects, through class library in visual studio and then access the methods in c# in unity and build the final app from unity 

Thank you 
Best regards

**Comment by SuavePirate** [comment]
In theory yeah. You could take the source out of the application projects and into class libraries than build for each platform. Those could then be exposed to your scripts in Unity.
